<a href="https://colab.research.google.com/github/awhang/mnist-colab-excercise/blob/main/00_pytorch_fundamentals_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
An excercise to learn the basics of using PyTorch

In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [32]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Tensor Creation

In [33]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [34]:
scalar.ndim

0

In [35]:
scalar.item()

10

In [36]:
# vector
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [37]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([2])

In [39]:
# MATRIX 
MATRIX = torch.tensor([[4, 5],
                       [6, 7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [40]:
MATRIX.ndim
MATRIX[1]

tensor([6, 7])

In [41]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [4, 5, 7]],
                        [[10, 4, 5],
                        [3, 2, 7],
                         [12, -1, 3]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([2, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 5, 7]])

### Creating Random Tensors

In [46]:
# Create a random tensor of size (4, 5)
random_tensor = torch.rand(5, 4, 5)
random_tensor

tensor([[[0.7771, 0.7466, 0.9289, 0.3953, 0.1955],
         [0.9346, 0.5613, 0.8780, 0.3281, 0.2727],
         [0.7604, 0.7940, 0.3693, 0.0702, 0.8067],
         [0.1335, 0.6871, 0.6330, 0.8418, 0.9302]],

        [[0.6269, 0.7153, 0.2140, 0.9890, 0.7773],
         [0.0316, 0.0018, 0.7730, 0.3657, 0.8520],
         [0.3097, 0.1773, 0.7718, 0.2642, 0.7776],
         [0.2082, 0.6155, 0.2438, 0.6528, 0.4068]],

        [[0.2112, 0.1751, 0.2014, 0.0080, 0.4574],
         [0.4661, 0.3642, 0.5427, 0.0810, 0.8515],
         [0.1564, 0.4928, 0.3317, 0.6019, 0.5420],
         [0.9538, 0.2985, 0.6911, 0.8424, 0.2199]],

        [[0.7535, 0.3011, 0.4579, 0.6241, 0.6938],
         [0.2320, 0.7930, 0.4068, 0.0838, 0.2244],
         [0.3166, 0.3790, 0.8329, 0.4120, 0.7386],
         [0.1472, 0.1833, 0.9468, 0.2766, 0.3642]],

        [[0.1162, 0.1512, 0.6741, 0.8506, 0.2580],
         [0.1436, 0.2372, 0.4232, 0.9159, 0.1513],
         [0.1245, 0.3271, 0.8639, 0.0133, 0.7247],
         [0.6213, 0.121

In [47]:
random_tensor.ndim

3

In [48]:
# Creating a random tensor similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, color channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [49]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [50]:
zeros*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [51]:
# Creating a tensor of all ones
ones = torch.ones(size=(4, 5), dtype=(torch.int8))
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

In [52]:
ones.dtype

torch.int8

### Creating a range of tensors and tensors-like

In [53]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

Tensor datatypes are one of the biggest issues you run into when using PyTorch and deep learning.

1. Incorrect datatype - to get datatype, can use `tensor.dtype`
2. Incorrect shape - to get shape, cna use `tensor.shape`
3. Not on the correct device - to get device, can use `tensor.device`

In [55]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what datatype the tensor is (e.g. int8, float64, etc)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:
float_32_tensor.dtype

torch.float16

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [60]:
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [62]:
# Create a tensor
some_tensor = torch.rand(5, 6)
some_tensor

tensor([[0.5407, 0.0061, 0.5161, 0.0421, 0.9816, 0.1441],
        [0.1078, 0.3454, 0.7797, 0.6090, 0.3795, 0.5083],
        [0.8630, 0.8866, 0.2404, 0.1713, 0.5816, 0.8743],
        [0.5686, 0.8823, 0.1751, 0.5070, 0.8986, 0.6935],
        [0.4573, 0.9910, 0.6167, 0.9442, 0.7817, 0.6753]])

In [63]:
# Find out some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5407, 0.0061, 0.5161, 0.0421, 0.9816, 0.1441],
        [0.1078, 0.3454, 0.7797, 0.6090, 0.3795, 0.5083],
        [0.8630, 0.8866, 0.2404, 0.1713, 0.5816, 0.8743],
        [0.5686, 0.8823, 0.1751, 0.5070, 0.8986, 0.6935],
        [0.4573, 0.9910, 0.6167, 0.9442, 0.7817, 0.6753]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 6])
Device of tensor: cpu


## Tensor Operations

Tensor operations includE:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [67]:
# Create a tensor and add 3 to it
tensor = torch.tensor([1, 2, 3])
tensor + 3

tensor([4, 5, 6])

In [68]:
# Multiply tensor by 3
tensor * 3

tensor([3, 6, 9])

In [69]:
# Subtract tensor by 3
tensor - 3

tensor([-2, -1,  0])

In [70]:
# Try PyTorch in-built functions
torch.mul(tensor, 3)

tensor([3, 6, 9])

### Matrix Multiplication (scalar and dot product)

Two main ways of performing multiplication in neural networks and deep learning:
1. Scalar (Element-wise multiplication)
2. Dot product

In [71]:
# Scalar
print(f"{tensor} * {tensor} equals = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals = tensor([1, 4, 9])


In [73]:
# Dot Product
print(f"{tensor} dot {tensor} equals = {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) dot tensor([1, 2, 3]) equals = 14


### Finding the min, max, mean, sum, etc

In [93]:
# Create a tensor
x = torch.arange(1, 102, 10)
x

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [77]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [78]:
# Find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [82]:
# Find the mean - requires dtype of float or complex 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(50.), tensor(50.))

In [83]:
# Find the sum
torch.sum(x), x.sum()

(tensor(550.), tensor(550.))

### Finding the positional min and max

In [ ]:
x

In [94]:
# Finds the position (index value) in the tensor that has the minimum value with argmin()
x.argmin(), x[0]

(tensor(0), tensor(1))

In [96]:
# # Finds the position (index value) in the tensor that has the maximum value with argmin()
x.argmax(), x[10]

(tensor(10), tensor(101))

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an inupt tensor to a defined shape 
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors by certain  dimension 
  * e.g. `torch.vstack`, `torch.hstack`
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [183]:
# Let's create a tensor
import torch 
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [163]:
# Add a dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [118]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]), tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [146]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x * -1, x + 1, x * -2], dim=1)
x_stacked

tensor([[  1.,  -1.,   2.,  -2.],
        [  2.,  -2.,   3.,  -4.],
        [  3.,  -3.,   4.,  -6.],
        [  4.,  -4.,   5.,  -8.],
        [  5.,  -5.,   6., -10.],
        [  6.,  -6.,   7., -12.],
        [  7.,  -7.,   8., -14.],
        [  8.,  -8.,   9., -16.],
        [  9.,  -9.,  10., -18.]])

In [148]:
# Try using torch.vstack - seems easier to use vstack since the `dim=0` is unnecessary
x_vstack = torch.vstack([x, x * -1, x + 1, x * -2])
x_vstack

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9.],
        [  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18.]])

In [144]:
# Try using torch.hstack - does not seem to be as simple/easy a s using torch.stack with `dim=1`
x_hstack = torch.hstack((x, x * -1, x))
x_hstack

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., -1., -2., -3., -4., -5.,
        -6., -7., -8., -9.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [164]:
# Try torch.squeeze() -removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [168]:
# Try torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimensions with unsqueeze on the 0th dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [173]:
# Try torch.permute - rearranges the dims of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts the colour_channel to the first (0th) dimension

print(f"Original shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [186]:
x_original[0, 0, 0] = 1234
print(f"New value in original is {x_original[0, 0, 0]}")
print(f"New value in permuted is {x_permuted[0, 0, 0]}")

Original value is 1.0
New value in original is 1234.0
New value in permuted is 1234.0


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [187]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [188]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [198]:
# Index on the middle bracket (dim=1)
x[0, 2]

tensor([7, 8, 9])

In [197]:
# Index in the innermost bracket [ last dimensions ]

x[0, 2, 2]

tensor(9)

In [200]:
# You can also use ":" to selecet "all of a target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [205]:
# Get all values of 0th and 1st dimensions but only index  1 of 2nd dimension
x[:, 1, :]

tensor([[4, 5, 6]])

## PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it
* Data in NumPy, but you want it in a PyTorch tensor -> `torch.from_numpy(ndarray)`
* From PyTorch tensor to NumPy array -> `torch.Tensor.numpy()`

In [220]:
# NumPy array to tensor
import torch
import numpy as np

# numpy's default datatype is float64, but tensor's default datatype is float32
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # use .type method to change to float32 as needed
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [221]:
# Change the value of array, and what will this do to `tensor`?
array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [222]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [223]:
# Change the tensor, and what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( taking the randomness out of random )

How does a neural network learn?

`start with random numbers -> tensor operations -> update the random numbers to try and make them better represent the data -> rinse -> repeat`

To reduce the randomness, PyTorch comes with the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness

https://pytorch.org/docs/stable/notes/randomness.html

In [228]:
import torch

# Create two random tensors

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.2719, 0.4632, 0.7671, 0.5024],
        [0.1025, 0.7600, 0.8035, 0.7653],
        [0.8709, 0.7231, 0.8364, 0.5820]])
tensor([[0.8395, 0.0595, 0.4315, 0.4425],
        [0.2622, 0.6301, 0.8775, 0.1626],
        [0.2438, 0.3382, 0.8847, 0.0763]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [227]:
# Create random but reproducible tensors by using a random seed

import torch

# Set the random seed
RANDOM_SEED = 11

torch.manual_seed(RANDOM_SEED) # must use the seed for each random generation
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # must use the seed for each random generation
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])
tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs makes things go fast

GPUs are cool

from abc import update_abstractmethods
### 1. Getting a GPU
1. Easiest - Use Google Colab to use a GPU for free (or use Pro for even better GPUs)
2. Use your own GPU - takes some money and some time to set up
3. Use cloud computing - GCP, AWS, Azure, etc, allows you to rent computers on the cloud

### 2. Check for GPU access with PyTorch

It is recommended to set up agnostic code. 
Here are some best practices: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [229]:
# Check GPU access
import torch
torch.cuda.is_available()

False

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [231]:
# Count number of devices - useful for when you are running models on specific cuda devices and more.
torch.cuda.device_count()

0

### 3. Putting tensors and models on the GPUs

GPUs make things go brr

In [2]:
# Create tensor (defaul is on cpu)
import torch
tensor = torch.tensor([1, 2 , 3], device=None)

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# Tensor using device agnostic code to move the tensor to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu" # copied from above so this is runnable in the same code block

tensor_on_gpu = tensor.to(device) # .to() to move tensor to device
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [10]:
# If tensor is on GPU, unable to transform it to NumPy so move tensor back to CPU 

tensor_on_gpu.cpu().numpy() # .cpu() is same as .to("cpu")

array([1, 2, 3])

## Exercies

Source: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [19]:
# Set up environment
import torch
import numpy as np

In [20]:
# 2. Create a random tensor with shape (7, 7)

random_tensor_2 = torch.rand(7, 7)
random_tensor_2

tensor([[0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447],
        [0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196],
        [0.2147, 0.2816, 0.6679, 0.7878, 0.5070, 0.3055, 0.7738]])

In [26]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) 
#    (hint: you may have to transpose the second tensor).

random_tensor_3 = torch.rand(1, 7).T

answer_tensor = torch.matmul(random_tensor_2, random_tensor_3)
answer_tensor

tensor([[1.3770],
        [1.3179],
        [1.7218],
        [1.0046],
        [1.0905],
        [1.1290],
        [1.3568]])

In [32]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(seed=0)
random_tensor_2 = torch.rand(7, 7)
random_tensor_3 = torch.rand(1, 7).T

answer_tensor = torch.matmul(random_tensor_2, random_tensor_3)
answer_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [33]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
#    (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(seed=1234)

In [6]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) 

torch.manual_seed(seed=11)
random_tensor_A = torch.rand(2, 3)

torch.manual_seed(seed=11)
random_tensor_B = torch.rand(2, 3)


In [41]:
# 7. Perform a matrix multiplication on the tensors you created in 6 

torch.manual_seed(seed=0)
dot_of_A_B = torch.matmul(random_tensor_A, random_tensor_B.T)
dot_of_A_B

tensor([[1.2305, 0.9929],
        [0.9929, 0.8504]])

In [12]:
# 8. Find the maximum and minimum values of the output of 7.

print(f"Maximum: {dot_of_A_B.max()}")
print(f"Minimum: {dot_of_A_B.min()}")

Maximum: 1.0773606300354004
Minimum: 0.6613529324531555


In [13]:
# 9. Find the maximum and minimum index values of the output of 7.

print(f"Index of Maximum: {dot_of_A_B.argmax()}")
print(f"Index of Minimum: {dot_of_A_B.argmin()}")

Index of Maximum: 0
Index of Minimum: 3


In [16]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
#     Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(seed=7)
random_tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = random_tensor.squeeze()

print(f"First tensor: {random_tensor}")
print(f"First tensor shape: {random_tensor.shape}")
print(f"Second tensor: {squeezed_tensor}")
print(f"Second tensor shape: {squeezed_tensor.shape}")

First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
First tensor shape: torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Second tensor shape: torch.Size([10])
