<a href="https://colab.research.google.com/github/awhang/mnist-colab-excercise/blob/main/pytorch_fundamentals_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
An excercise to learn the basics of using PyTorch

In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [32]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Tensor Creation

In [33]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [34]:
scalar.ndim

0

In [35]:
scalar.item()

10

In [36]:
# vector
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [37]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([2])

In [39]:
# MATRIX 
MATRIX = torch.tensor([[4, 5],
                       [6, 7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [40]:
MATRIX.ndim
MATRIX[1]

tensor([6, 7])

In [41]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [4, 5, 7]],
                        [[10, 4, 5],
                        [3, 2, 7],
                         [12, -1, 3]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([2, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 5, 7]])

### Creating Random Tensors

In [46]:
# Create a random tensor of size (4, 5)
random_tensor = torch.rand(5, 4, 5)
random_tensor

tensor([[[0.7771, 0.7466, 0.9289, 0.3953, 0.1955],
         [0.9346, 0.5613, 0.8780, 0.3281, 0.2727],
         [0.7604, 0.7940, 0.3693, 0.0702, 0.8067],
         [0.1335, 0.6871, 0.6330, 0.8418, 0.9302]],

        [[0.6269, 0.7153, 0.2140, 0.9890, 0.7773],
         [0.0316, 0.0018, 0.7730, 0.3657, 0.8520],
         [0.3097, 0.1773, 0.7718, 0.2642, 0.7776],
         [0.2082, 0.6155, 0.2438, 0.6528, 0.4068]],

        [[0.2112, 0.1751, 0.2014, 0.0080, 0.4574],
         [0.4661, 0.3642, 0.5427, 0.0810, 0.8515],
         [0.1564, 0.4928, 0.3317, 0.6019, 0.5420],
         [0.9538, 0.2985, 0.6911, 0.8424, 0.2199]],

        [[0.7535, 0.3011, 0.4579, 0.6241, 0.6938],
         [0.2320, 0.7930, 0.4068, 0.0838, 0.2244],
         [0.3166, 0.3790, 0.8329, 0.4120, 0.7386],
         [0.1472, 0.1833, 0.9468, 0.2766, 0.3642]],

        [[0.1162, 0.1512, 0.6741, 0.8506, 0.2580],
         [0.1436, 0.2372, 0.4232, 0.9159, 0.1513],
         [0.1245, 0.3271, 0.8639, 0.0133, 0.7247],
         [0.6213, 0.121

In [47]:
random_tensor.ndim

3

In [48]:
# Creating a random tensor similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, color channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [49]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [50]:
zeros*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [51]:
# Creating a tensor of all ones
ones = torch.ones(size=(4, 5), dtype=(torch.int8))
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

In [52]:
ones.dtype

torch.int8

### Creating a range of tensors and tensors-like

In [53]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

Tensor datatypes are one of the biggest issues you run into when using PyTorch and deep learning.

1. Incorrect datatype - to get datatype, can use `tensor.dtype`
2. Incorrect shape - to get shape, cna use `tensor.shape`
3. Not on the correct device - to get device, can use `tensor.device`

In [55]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what datatype the tensor is (e.g. int8, float64, etc)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:
float_32_tensor.dtype

torch.float16

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [60]:
int_32_tensor = torch.tensor([3, 6, 9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [62]:
# Create a tensor
some_tensor = torch.rand(5, 6)
some_tensor

tensor([[0.5407, 0.0061, 0.5161, 0.0421, 0.9816, 0.1441],
        [0.1078, 0.3454, 0.7797, 0.6090, 0.3795, 0.5083],
        [0.8630, 0.8866, 0.2404, 0.1713, 0.5816, 0.8743],
        [0.5686, 0.8823, 0.1751, 0.5070, 0.8986, 0.6935],
        [0.4573, 0.9910, 0.6167, 0.9442, 0.7817, 0.6753]])

In [63]:
# Find out some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5407, 0.0061, 0.5161, 0.0421, 0.9816, 0.1441],
        [0.1078, 0.3454, 0.7797, 0.6090, 0.3795, 0.5083],
        [0.8630, 0.8866, 0.2404, 0.1713, 0.5816, 0.8743],
        [0.5686, 0.8823, 0.1751, 0.5070, 0.8986, 0.6935],
        [0.4573, 0.9910, 0.6167, 0.9442, 0.7817, 0.6753]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 6])
Device of tensor: cpu


### Tensor Operations

Tensor operations includE:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [67]:
# Create a tensor and add 3 to it
tensor = torch.tensor([1, 2, 3])
tensor + 3

tensor([4, 5, 6])

In [68]:
# Multiply tensor by 3
tensor * 3

tensor([3, 6, 9])

In [69]:
# Subtract tensor by 3
tensor - 3

tensor([-2, -1,  0])

In [70]:
# Try PyTorch in-built functions
torch.mul(tensor, 3)

tensor([3, 6, 9])

### Matrix Multiplication (scalar and dot product)

Two main ways of performing multiplication in neural networks and deep learning:
1. Scalar (Element-wise multiplication)
2. Dot product

In [71]:
# Scalar
print(f"{tensor} * {tensor} equals = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals = tensor([1, 4, 9])


In [73]:
# Dot Product
print(f"{tensor} dot {tensor} equals = {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) dot tensor([1, 2, 3]) equals = 14


### Finding the min, max, mean, sum, etc

In [93]:
# Create a tensor
x = torch.arange(1, 102, 10)
x

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [77]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [78]:
# Find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [82]:
# Find the mean - requires dtype of float or complex 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(50.), tensor(50.))

In [83]:
# Find the sum
torch.sum(x), x.sum()

(tensor(550.), tensor(550.))

### Finding the positional min and max

In [ ]:
x

In [94]:
# Finds the position (index value) in the tensor that has the minimum value with argmin()
x.argmin(), x[0]

(tensor(0), tensor(1))

In [96]:
# # Finds the position (index value) in the tensor that has the maximum value with argmin()
x.argmax(), x[10]

(tensor(10), tensor(101))

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an inupt tensor to a defined shape 
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors by certain  dimension 
  * e.g. `torch.vstack`, `torch.hstack`
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [183]:
# Let's create a tensor
import torch 
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [163]:
# Add a dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [118]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]), tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [146]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x * -1, x + 1, x * -2], dim=1)
x_stacked

tensor([[  1.,  -1.,   2.,  -2.],
        [  2.,  -2.,   3.,  -4.],
        [  3.,  -3.,   4.,  -6.],
        [  4.,  -4.,   5.,  -8.],
        [  5.,  -5.,   6., -10.],
        [  6.,  -6.,   7., -12.],
        [  7.,  -7.,   8., -14.],
        [  8.,  -8.,   9., -16.],
        [  9.,  -9.,  10., -18.]])

In [148]:
# Try using torch.vstack - seems easier to use vstack since the `dim=0` is unnecessary
x_vstack = torch.vstack([x, x * -1, x + 1, x * -2])
x_vstack

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9.],
        [  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18.]])

In [144]:
# Try using torch.hstack - does not seem to be as simple/easy a s using torch.stack with `dim=1`
x_hstack = torch.hstack((x, x * -1, x))
x_hstack

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., -1., -2., -3., -4., -5.,
        -6., -7., -8., -9.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [164]:
# Try torch.squeeze() -removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [168]:
# Try torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimensions with unsqueeze on the 0th dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [173]:
# Try torch.permute - rearranges the dims of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts the colour_channel to the first (0th) dimension

print(f"Original shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [186]:
x_original[0, 0, 0] = 1234
print(f"New value in original is {x_original[0, 0, 0]}")
print(f"New value in permuted is {x_permuted[0, 0, 0]}")

Original value is 1.0
New value in original is 1234.0
New value in permuted is 1234.0


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [187]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [188]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [198]:
# Index on the middle bracket (dim=1)
x[0, 2]

tensor([7, 8, 9])

In [197]:
# Index in the innermost bracket [ last dimensions ]

x[0, 2, 2]

tensor(9)

In [200]:
# You can also use ":" to selecet "all of a target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [205]:
# Get all values of 0th and 1st dimensions but only index  1 of 2nd dimension
x[:, 1, :]

tensor([[4, 5, 6]])

## PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it
* Data in NumPy, but you want it in a PyTorch tensor -> `torch.from_numpy(ndarray)`
* From PyTorch tensor to NumPy array -> `torch.Tensor.numpy()`

In [220]:
# NumPy array to tensor
import torch
import numpy as np

# numpy's default datatype is float64, but tensor's default datatype is float32
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # use .type method to change to float32 as needed
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [221]:
# Change the value of array, and what will this do to `tensor`?
array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [222]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [223]:
# Change the tensor, and what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility ( taking the randomness out of random )

How does a neural network learn?

`start with random numbers -> tensor operations -> update the random numbers to try and make them better represent the data -> rinse -> repeat`

To reduce the randomness, PyTorch comes with the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness

In [224]:
import torch

# Create two random tensors

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.4662, 0.1429, 0.1365, 0.2565],
        [0.5465, 0.0587, 0.1069, 0.6711],
        [0.6807, 0.7996, 0.5264, 0.8784]])
tensor([[0.5324, 0.6774, 0.9643, 0.6811],
        [0.9080, 0.3197, 0.8955, 0.4395],
        [0.9950, 0.3028, 0.5006, 0.9429]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
