<a href="https://colab.research.google.com/github/awhang/mnist-colab-excercise/blob/main/pytorch_fundamentals_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MNIST PyTorch Practice
An excercise using pytorch to practice using neural networks for image recognition with the MNIST digit data set.

In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [32]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Tensor Creation

In [33]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [34]:
scalar.ndim

0

In [35]:
scalar.item()

10

In [36]:
# vector
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [37]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([2])

In [39]:
# MATRIX 
MATRIX = torch.tensor([[4, 5],
                       [6, 7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [40]:
MATRIX.ndim
MATRIX[1]

tensor([6, 7])

In [41]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [4, 5, 7]],
                        [[10, 4, 5],
                        [3, 2, 7],
                         [12, -1, 3]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([2, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 5, 7]])

# Creating Random Tensors

In [46]:
# Create a random tensor of size (4, 5)
random_tensor = torch.rand(5, 4, 5)
random_tensor

tensor([[[0.7771, 0.7466, 0.9289, 0.3953, 0.1955],
         [0.9346, 0.5613, 0.8780, 0.3281, 0.2727],
         [0.7604, 0.7940, 0.3693, 0.0702, 0.8067],
         [0.1335, 0.6871, 0.6330, 0.8418, 0.9302]],

        [[0.6269, 0.7153, 0.2140, 0.9890, 0.7773],
         [0.0316, 0.0018, 0.7730, 0.3657, 0.8520],
         [0.3097, 0.1773, 0.7718, 0.2642, 0.7776],
         [0.2082, 0.6155, 0.2438, 0.6528, 0.4068]],

        [[0.2112, 0.1751, 0.2014, 0.0080, 0.4574],
         [0.4661, 0.3642, 0.5427, 0.0810, 0.8515],
         [0.1564, 0.4928, 0.3317, 0.6019, 0.5420],
         [0.9538, 0.2985, 0.6911, 0.8424, 0.2199]],

        [[0.7535, 0.3011, 0.4579, 0.6241, 0.6938],
         [0.2320, 0.7930, 0.4068, 0.0838, 0.2244],
         [0.3166, 0.3790, 0.8329, 0.4120, 0.7386],
         [0.1472, 0.1833, 0.9468, 0.2766, 0.3642]],

        [[0.1162, 0.1512, 0.6741, 0.8506, 0.2580],
         [0.1436, 0.2372, 0.4232, 0.9159, 0.1513],
         [0.1245, 0.3271, 0.8639, 0.0133, 0.7247],
         [0.6213, 0.121

In [47]:
random_tensor.ndim

3

In [48]:
# Creating a random tensor similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigh, width, color channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [49]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [50]:
zeros*random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [51]:
# Creating a tensor of all ones
ones = torch.ones(size=(4, 5), dtype=(torch.int8))
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

In [52]:
ones.dtype

torch.int8

# Creating a range of tensors and tensors-like

In [53]:
# Use torch.arange()

one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

Tensor datatypes are one of the biggest issues you run into when using PyTorch and deep learning.

1. Incorrect datatype
2. Incorrect shape
3. Not on the correct device

In [55]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what datatype the tensor is (e.g. int8, float64, etc)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:
float_32_tensor.dtype

torch.float16

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)